# Generated by Django 6.0.2 on 2026-02-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short summary of the support issue', max_length=200)),
                ('description', models.TextField(help_text='Full description of the problem')),
                ('category', models.CharField(choices=[('billing', 'Billing'), ('technical', 'Technical'), ('account', 'Account'), ('general', 'General')], default='general', help_text='Ticket category — auto-suggested by LLM, user can override', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Ticket priority — auto-suggested by LLM, user can override', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current workflow status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the ticket was created')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='idx_ticket_category'), models.Index(fields=['priority'], name='idx_ticket_priority'), models.Index(fields=['status'], name='idx_ticket_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['billing', 'technical', 'account', 'general'])), name='valid_category'), models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'medium', 'high', 'critical'])), name='valid_priority'), models.CheckConstraint(condition=models.Q(('status__in', ['open', 'in_progress', 'resolved', 'closed'])), name='valid_status')],
            },
        ),
    ]
